// Action groups and metadata for the Controls tab
// Inspired by the NetHack keyboard reference PDF for familiarity.

export const KEY_GROUPS = [
  // Movement (primary 4-way + diagonals + wait)
  {
    id: 'movement',
    title: 'Movement',
    quip: '',
    actions: [
      { id: 'moveUp', label: 'Move Up' },
      { id: 'moveDown', label: 'Move Down' },
      { id: 'moveLeft', label: 'Move Left' },
      { id: 'moveRight', label: 'Move Right' },
      { id: 'moveUpLeft', label: 'Move Up-Left' },
      { id: 'moveUpRight', label: 'Move Up-Right' },
      { id: 'moveDownLeft', label: 'Move Down-Left' },
      { id: 'moveDownRight', label: 'Move Down-Right' },
      { id: 'waitTurn', label: 'Wait/Rest' },
    ],
  },
  // Movement (secondary bindings, used by the second ring; not rendered directly)
  {
    id: 'movementSecondary',
    title: 'Movement (Secondary)',
    quip: 'Secondary bindings used by the right-hand movement ring.',
    actions: [
      { id: 'moveUp2', label: 'Move Up (Secondary)' },
      { id: 'moveDown2', label: 'Move Down (Secondary)' },
      { id: 'moveLeft2', label: 'Move Left (Secondary)' },
      { id: 'moveRight2', label: 'Move Right (Secondary)' },
      { id: 'moveUpLeft2', label: 'Move Up-Left (Secondary)' },
      { id: 'moveUpRight2', label: 'Move Up-Right (Secondary)' },
      { id: 'moveDownLeft2', label: 'Move Down-Left (Secondary)' },
      { id: 'moveDownRight2', label: 'Move Down-Right (Secondary)' },
      { id: 'waitTurn2', label: 'Wait/Rest (Secondary)' },
    ],
  },
  // Movement (advanced)
  {
    id: 'movementAdvanced',
    title: 'Movement (Additional)',
    quip: '',
    actions: [
      { id: 'ascendStairs', label: 'Ascend Stairs' },
      { id: 'descendStairs', label: 'Descend Stairs' },
      { id: 'quickMove', label: 'Quick Move' },
      { id: 'moveFar', label: 'Move Far' },
      { id: 'jump', label: 'Jump' },
      { id: 'teleport', label: 'Teleport' },
      { id: 'autoTravel', label: 'Auto-Travel/Run' },
      { id: 'rideMonster', label: 'Ride Monster' },
      { id: 'sitDown', label: 'Sit Down' },
    ],
  },
  // Interaction / environment
  {
    id: 'interaction',
    title: 'Interaction',
    quip: '',
    actions: [
      { id: 'search', label: 'Search' },
      { id: 'look', label: 'Look/Examine' },
      { id: 'open', label: 'Open' },
      { id: 'close', label: 'Close' },
      { id: 'kick', label: 'Kick' },
      { id: 'lootContainer', label: 'Loot Box/Bag' },
      { id: 'untrap', label: 'Untrap' },
      { id: 'forceLock', label: 'Force Lock' },
      { id: 'identifySymbol', label: 'Identify Symbol' },
      { id: 'identifyTrap', label: 'Identify Trap' },
      { id: 'nameMonster', label: 'Name Monster' },
      { id: 'wipeFace', label: 'Wipe Face' },
      { id: 'engrave', label: 'Engrave' },
      { id: 'writeInscription', label: 'Write Inscription' },
      { id: 'pay', label: 'Pay' },
    ],
  },
  // Magic & Spiritual
  {
    id: 'magic',
    title: 'Magic & Spiritual',
    quip: '',
    actions: [
      { id: 'castSpell', label: 'Cast Spell' },
      { id: 'drink', label: 'Drink' },
      { id: 'zapWand', label: 'Zap Wand' },
      { id: 'pray', label: 'Pray' },
      { id: 'dip', label: 'Dip' },
      { id: 'rub', label: 'Rub' },
      { id: 'offer', label: 'Offer/Sacrifice' },
      { id: 'invoke', label: 'Invoke' },
      { id: 'turnUndead', label: 'Turn Undead' },
      { id: 'specialAbility', label: 'Special Ability' },
      { id: 'breakWand', label: 'Break Wand' },
    ],
  },
  // Combat
  {
    id: 'combat',
    title: 'Combat',
    quip: '',
    actions: [
      { id: 'wield', label: 'Wield Weapon' },
      { id: 'swapWeapon', label: 'Swap Weapon' },
      { id: 'throw', label: 'Throw' },
      { id: 'fire', label: 'Fire (Quiver)' },
      { id: 'targetNext', label: 'Next Target' },
      { id: 'twoWeapon', label: 'Use Two Weapons' },
      { id: 'viewSkills', label: 'View Skills' },
      { id: 'raiseSkills', label: 'Raise Skills' },
    ],
  },
  // Inventory & items
  {
    id: 'inventory',
    title: 'Inventory & Items',
    quip: '',
    actions: [
      { id: 'inventory', label: 'Open Inventory' },
      { id: 'pickup', label: 'Pick Up' },
      { id: 'drop', label: 'Drop' },
      { id: 'dropMany', label: 'Drop Many' },
      { id: 'apply', label: 'Apply/Use' },
      { id: 'eat', label: 'Eat' },
      { id: 'read', label: 'Read' },
      { id: 'quaff', label: 'Quaff' },
      { id: 'wear', label: 'Wear/Put On' },
      { id: 'remove', label: 'Remove/Take Off' },
      { id: 'quiverSelect', label: 'Select Quiver' },
      { id: 'adjustInventory', label: 'Adjust Inventory' },
      { id: 'nameObject', label: 'Name Object' },
      { id: 'wearArmor', label: 'Wear Armor' },
      { id: 'takeoffArmor', label: 'Take Off Armor' },
      { id: 'removeMulti', label: 'Remove Multiple Items' },
      { id: 'putOnRingAmulet', label: 'Put On Ring/Amulet' },
      { id: 'removeRingAmulet', label: 'Remove Ring/Amulet' },
    ],
  },
  // Lists (moved out of Inventory & Items)
  {
    id: 'lists',
    title: 'Lists',
    quip: '',
    actions: [
      { id: 'listWeapons', label: 'List Weapons' },
      { id: 'listArmor', label: 'List Armor' },
      { id: 'listRings', label: 'List Rings' },
      { id: 'listAmulets', label: 'List Amulets' },
      { id: 'listTools', label: 'List Tools' },
      { id: 'listEquipment', label: 'List Equipment' },
      { id: 'listGold', label: 'List Gold' },
      { id: 'listSpells', label: 'List Spells' },
      { id: 'listDiscoveries', label: 'List Discovered Objects' },
      { id: 'listChallenges', label: 'List Challenges' },
    ],
  },
  // Extended Commands (two-keystroke): prefix + letter
  {
    id: 'extended',
    title: 'Extended Commands',
    quip: 'Two-keystroke commands: [prefix] + [key] (e.g., # + r = Ride).',
    actions: [
      { id: 'extendedPrefix', label: 'Extended Prefix' },
      { id: 'extHelp', label: 'Help' },
      { id: 'extJump', label: 'Jump' },
      { id: 'extRide', label: 'Ride' },
      { id: 'extLoot', label: 'Loot Box / Bag' },
      { id: 'extUntrap', label: 'Untrap' },
      { id: 'extTwoWeapon', label: 'Two Weapons' },
      { id: 'extNameObject', label: 'Name Object' },
      { id: 'extListChallenges', label: 'List Challenges' },
    ],
  },
  // System & UI
  {
    id: 'system',
    title: 'System & UI',
    quip: '',
    actions: [
      { id: 'help', label: 'Help' },
      { id: 'messageHistory', label: 'Message History' },
      { id: 'options', label: 'Options/Settings' },
      { id: 'saveQuit', label: 'Save & Quit' },
      { id: 'fullscreenToggle', label: 'Toggle Fullscreen' },
      { id: 'playerInfo', label: 'Player Info' },
      { id: 'save', label: 'Save' },
      { id: 'quit', label: 'Quit' },
      { id: 'redo', label: 'Redo' },
      { id: 'talk', label: 'Talk/Chat' },
      { id: 'repeatMessage', label: 'Repeat Message' },
      { id: 'toggleAutopickup', label: 'Toggle Auto-pickup' },
      { id: 'displayVersion', label: 'Display Version' },
      { id: 'displayHistory', label: 'Display History' },
      { id: 'exploreMode', label: 'Explore Mode' },
      { id: 'explainCommand', label: 'Explain Command' },
      { id: 'redrawScreen', label: 'Redraw the Screen' },
      { id: 'suspend', label: 'Suspend' },
      { id: 'bossKey', label: 'Boss Key' },
    ],
  },
];
